-- Create Transports Table
create table if not exists transports (
  id bigint generated by default as identity primary key,
  name text not null,
  type text check (type in ('local', 'metro', 'ac-local')),
  capacity int default 2000,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Create Routes Table
create table if not exists routes (
  id bigint generated by default as identity primary key,
  name text not null,
  stations jsonb, -- Array of station names
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Create Occupancy Logs / Real-time Status Table
create table if not exists transport_status (
  id bigint generated by default as identity primary key,
  transport_id bigint references transports(id),
  route_id bigint references routes(id),
  current_occupancy int default 0,
  status text check (status in ('Low', 'Medium', 'High')) default 'Low',
  last_updated timestamp with time zone default timezone('utc'::text, now())
);

-- Seed Data (Optional - Run manually if needed)
insert into transports (name, type, capacity) values 
('Fast Local', 'local', 2000),
('Slow Local', 'local', 2000),
('AC Local', 'ac-local', 1500),
('Metro Line 3', 'metro', 1200);

insert into routes (name, stations) values 
('Churchgate - Virar', '["Churchgate", "Mumbai Central", "Dadar", "Bandra", "Andheri", "Borivali", "Virar"]'),
('Churchgate - Borivali', '["Churchgate", "Marine Lines", "Charni Road", "Grant Road", "Mumbai Central", "Dadar", "Bandra", "Andheri", "Borivali"]'),
('Cuffe Parade - SEEPZ', '["Cuffe Parade", "Vidhan Bhavan", "Churchgate", "Hutatma Chowk", "CST", "Kalbadevi", "Girgaon", "Grant Road", "Mumbai Central", "Mahalaxmi", "Science Museum", "Worli", "Siddhivinayak", "Dadar", "Sheetaladevi", "Dharavi", "BKC", "Vidyanagari", "Santacruz", "CSIA Domestic", "Sahar Road", "CSIA International", "Marol Naka", "MIDC", "SEEPZ"]');

-- Initialize Status for Seeded Transports
insert into transport_status (transport_id, route_id, current_occupancy, status) values
(1, 1, 1850, 'High'),
(2, 2, 800, 'Medium'),
(3, 1, 200, 'Low'),
(4, 3, 600, 'Medium');
